using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyFordonsInfo
{
    public class Vehicle
    {
        public static string[] headers = new string[] { 
            "Fordonsidentifikation",
            "Registreringsnummer",
            "Fabrikat",
            "Färg",
            "Fordonsslag",
            "Fordonsår",
            "Fordonsslagsklass",
            "Identifieringsnummer",
            "Typgodkännandenummer",
            "Typgodkännandedatum",
            "Senaste EUregbevis","del {0}",
            "Handelsbeteckning",
            "Upplysningar",
            "Ägare/Brukare",
            "Namn",
            "Adress",
            "Postnr",
            "Förvärvsdatum",
            "Ort",
            "Försäkringsuppgifter",
            "Försäkringsbolag",
            "Försäkringsdatum",
            "Fordonsdata",
            "Fordonsstatus",
            "Tillfällig registrering",
            "Antal ägare",
            "Yrkesmässig trafik",
            "Fordonet tillverkat",
            "Producentansvarig",
            "I trafik första gången i Sverige",
            "I trafik första gången i utlandet",
            "Import/införsel",
            "Ägarbunden dispens",
            "Ägarbunden dispens upphör",
            "Besiktningsuppgifter",
            "Besiktningstermin",
            "Senast godkända besiktning",
            "Föreläggande",
            "Körförbud",
            "Vägmätarställning",
            "Skatteuppgifter",
            "Fordonsskattepliktigt",
            "Användningsförbud",
            "Trängselskattepliktigt",
            "Årsskatt, kr",
            "Debitering vid påställning(inkl. avgifter), kr",
            "Återbetalning vid avställning, kr",
            "Debiterad fordonsskatt, kr",
            "Debiterad avgift, kr",
            "Betalningsmånad/er",
            "Förfallen fordonsskatt/avgift, kr",
            "Vägtrafikregisteravgift",
            "Tekniska data",
            "Motornummer",
            "Kaross",
            "Karosserikod tillägg",
            "Karosserikod särskilda ändamål",
            "Slagvolym, cm3",
            "Växellåda",
            "Antal passagerare, max",
            "Antal sittande passagerare, max",
            "Antal bältade passagerare, max",
            "Antal passagerare i rullstol, max",
            "Antal stående passagerare, max",
            "Skattevikt, kg",
            "Tjänstevikt, kg",
            "Totalvikt, kg",
            "Ursprunglig totalvikt, kg",
            "Max släpvagnsvikt, kg",
            "Max släpvikt kg, obromsad",
            "Släpets maximala totalvikt vid körkortsbehörighet B",
            "Släpets maximala totalvikt vid utökad körkortsbehörighet B",
            "Max sammanlagd bruttovikt, kg",
            "Max lastvikt, kg",
            "Kopplingsanordning ",
            "Kopplingsavstånd, mm",
            "Kopplingsavstånd EU, mm",
            "Max kopplingsavstånd EU, mm",
            "Tilläggsinformation",
            "Bromsuttag ",
            "Lastutrymmets längd, mm",
            "Främre överhäng, mm",
            "Bakre överhäng, mm",
            "Utrustning",
            "Drivande axlar fram",
            "Drivande axlar bak",
            "Antal hjul",
            "Max axelavstånd axel 1-2, mm",
            "Däckdimension axel {0}",
            "Fälgdimension axel {0}",
            "Bandbredd, mm",
            "Längd, mm",
            "Bredd, mm",
            "Höjd, mm",
            "Drivmedel {0}",
            "Motoreffekt, kW",
            "Effektnorm",
            "Max hastighet, km/h",
            "Ljudnivå dB, vid körning",
            "Ljudnivå dB, stillastående",
            "Varvtal stillastående min{0}",
            "Bränsleförbrukning, blandad körning",
            "Koldioxidutsläpp, CO2 blandad körning",
            "Bränsleförbrukning, landsvägskörning",
            "Koldioxidutsläpp, CO2 landsvägskörning",
            "Bränsleförbrukning, stadskörning",
            "Koldioxidutsläpp, CO2 stadskörning",
            "Röktäthet, M1",
            "Absorptionskoefficient, M1",
            "Avgasdirektiv/reglemente",
            "Kolmonoxid, CO",
            "Kväveoxider, NOX",
            "Kolväten och kväveoxider, THC + NOX",
            "Partiklar",
            "Miljöklass",
            "Miljöbilsklass",
            "Euro miljöklassning",
            "Utsläppsklass",
            "Skyltformat fram",
            "Skyltformat bak"
        };
    }
}
