//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace tv.hagser.se_sl.TvWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TvWebService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginGetInfo(string p, System.AsyncCallback callback, object asyncState);
        
        string EndGetInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ForceRefresh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginForceRefresh(string p, System.AsyncCallback callback, object asyncState);
        
        string EndForceRefresh(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetChannels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginGetChannels(System.AsyncCallback callback, object asyncState);
        
        Channel[] EndGetChannels(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetProgrammes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginGetProgrammes(tv.hagser.se_sl.TvWebService.GetProgrammesRequest request, System.AsyncCallback callback, object asyncState);
        
        tv.hagser.se_sl.TvWebService.GetProgrammesResponse EndGetProgrammes(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Channel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProgrammesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Programme[] programmesField;
        
        private string exceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Programme[] programmes {
            get {
                return this.programmesField;
            }
            set {
                this.programmesField = value;
                this.RaisePropertyChanged("programmes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("exception");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Programme : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startField;
        
        private System.DateTime stopField;
        
        private string channelField;
        
        private string channelnameField;
        
        private string titleField;
        
        private string episodenumField;
        
        private string subtitleField;
        
        private string descField;
        
        private Credit[] creditsField;
        
        private string dateField;
        
        private string[] categoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
                this.RaisePropertyChanged("stop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string channelname {
            get {
                return this.channelnameField;
            }
            set {
                this.channelnameField = value;
                this.RaisePropertyChanged("channelname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string episodenum {
            get {
                return this.episodenumField;
            }
            set {
                this.episodenumField = value;
                this.RaisePropertyChanged("episodenum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
                this.RaisePropertyChanged("subtitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public Credit[] credits {
            get {
                return this.creditsField;
            }
            set {
                this.creditsField = value;
                this.RaisePropertyChanged("credits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public string[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Credit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProgrammesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Programme programmeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Programme programme {
            get {
                return this.programmeField;
            }
            set {
                this.programmeField = value;
                this.RaisePropertyChanged("programme");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : tv.hagser.se_sl.TvWebService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForceRefreshCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ForceRefreshCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Channel[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Channel[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProgrammesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProgrammesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public tv.hagser.se_sl.TvWebService.GetProgrammesResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((tv.hagser.se_sl.TvWebService.GetProgrammesResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<tv.hagser.se_sl.TvWebService.Service1Soap>, tv.hagser.se_sl.TvWebService.Service1Soap {
        
        private BeginOperationDelegate onBeginGetInfoDelegate;
        
        private EndOperationDelegate onEndGetInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginForceRefreshDelegate;
        
        private EndOperationDelegate onEndForceRefreshDelegate;
        
        private System.Threading.SendOrPostCallback onForceRefreshCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetChannelsDelegate;
        
        private EndOperationDelegate onEndGetChannelsDelegate;
        
        private System.Threading.SendOrPostCallback onGetChannelsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProgrammesDelegate;
        
        private EndOperationDelegate onEndGetProgrammesDelegate;
        
        private System.Threading.SendOrPostCallback onGetProgrammesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetInfoCompletedEventArgs> GetInfoCompleted;
        
        public event System.EventHandler<ForceRefreshCompletedEventArgs> ForceRefreshCompleted;
        
        public event System.EventHandler<GetChannelsCompletedEventArgs> GetChannelsCompleted;
        
        public event System.EventHandler<GetProgrammesCompletedEventArgs> GetProgrammesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tv.hagser.se_sl.TvWebService.Service1Soap.BeginGetInfo(string p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInfo(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string tv.hagser.se_sl.TvWebService.Service1Soap.EndGetInfo(System.IAsyncResult result) {
            return base.Channel.EndGetInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string p = ((string)(inValues[0]));
            return ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).BeginGetInfo(p, callback, asyncState);
        }
        
        private object[] OnEndGetInfo(System.IAsyncResult result) {
            string retVal = ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).EndGetInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInfoCompleted(object state) {
            if ((this.GetInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInfoAsync(string p) {
            this.GetInfoAsync(p, null);
        }
        
        public void GetInfoAsync(string p, object userState) {
            if ((this.onBeginGetInfoDelegate == null)) {
                this.onBeginGetInfoDelegate = new BeginOperationDelegate(this.OnBeginGetInfo);
            }
            if ((this.onEndGetInfoDelegate == null)) {
                this.onEndGetInfoDelegate = new EndOperationDelegate(this.OnEndGetInfo);
            }
            if ((this.onGetInfoCompletedDelegate == null)) {
                this.onGetInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetInfoDelegate, new object[] {
                        p}, this.onEndGetInfoDelegate, this.onGetInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tv.hagser.se_sl.TvWebService.Service1Soap.BeginForceRefresh(string p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginForceRefresh(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string tv.hagser.se_sl.TvWebService.Service1Soap.EndForceRefresh(System.IAsyncResult result) {
            return base.Channel.EndForceRefresh(result);
        }
        
        private System.IAsyncResult OnBeginForceRefresh(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string p = ((string)(inValues[0]));
            return ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).BeginForceRefresh(p, callback, asyncState);
        }
        
        private object[] OnEndForceRefresh(System.IAsyncResult result) {
            string retVal = ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).EndForceRefresh(result);
            return new object[] {
                    retVal};
        }
        
        private void OnForceRefreshCompleted(object state) {
            if ((this.ForceRefreshCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ForceRefreshCompleted(this, new ForceRefreshCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ForceRefreshAsync(string p) {
            this.ForceRefreshAsync(p, null);
        }
        
        public void ForceRefreshAsync(string p, object userState) {
            if ((this.onBeginForceRefreshDelegate == null)) {
                this.onBeginForceRefreshDelegate = new BeginOperationDelegate(this.OnBeginForceRefresh);
            }
            if ((this.onEndForceRefreshDelegate == null)) {
                this.onEndForceRefreshDelegate = new EndOperationDelegate(this.OnEndForceRefresh);
            }
            if ((this.onForceRefreshCompletedDelegate == null)) {
                this.onForceRefreshCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnForceRefreshCompleted);
            }
            base.InvokeAsync(this.onBeginForceRefreshDelegate, new object[] {
                        p}, this.onEndForceRefreshDelegate, this.onForceRefreshCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tv.hagser.se_sl.TvWebService.Service1Soap.BeginGetChannels(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetChannels(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Channel[] tv.hagser.se_sl.TvWebService.Service1Soap.EndGetChannels(System.IAsyncResult result) {
            return base.Channel.EndGetChannels(result);
        }
        
        private System.IAsyncResult OnBeginGetChannels(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).BeginGetChannels(callback, asyncState);
        }
        
        private object[] OnEndGetChannels(System.IAsyncResult result) {
            Channel[] retVal = ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).EndGetChannels(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetChannelsCompleted(object state) {
            if ((this.GetChannelsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetChannelsCompleted(this, new GetChannelsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetChannelsAsync() {
            this.GetChannelsAsync(null);
        }
        
        public void GetChannelsAsync(object userState) {
            if ((this.onBeginGetChannelsDelegate == null)) {
                this.onBeginGetChannelsDelegate = new BeginOperationDelegate(this.OnBeginGetChannels);
            }
            if ((this.onEndGetChannelsDelegate == null)) {
                this.onEndGetChannelsDelegate = new EndOperationDelegate(this.OnEndGetChannels);
            }
            if ((this.onGetChannelsCompletedDelegate == null)) {
                this.onGetChannelsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetChannelsCompleted);
            }
            base.InvokeAsync(this.onBeginGetChannelsDelegate, null, this.onEndGetChannelsDelegate, this.onGetChannelsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tv.hagser.se_sl.TvWebService.Service1Soap.BeginGetProgrammes(tv.hagser.se_sl.TvWebService.GetProgrammesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProgrammes(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tv.hagser.se_sl.TvWebService.GetProgrammesResponse tv.hagser.se_sl.TvWebService.Service1Soap.EndGetProgrammes(System.IAsyncResult result) {
            return base.Channel.EndGetProgrammes(result);
        }
        
        private System.IAsyncResult OnBeginGetProgrammes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            tv.hagser.se_sl.TvWebService.GetProgrammesRequest request = ((tv.hagser.se_sl.TvWebService.GetProgrammesRequest)(inValues[0]));
            return ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).BeginGetProgrammes(request, callback, asyncState);
        }
        
        private object[] OnEndGetProgrammes(System.IAsyncResult result) {
            tv.hagser.se_sl.TvWebService.GetProgrammesResponse retVal = ((tv.hagser.se_sl.TvWebService.Service1Soap)(this)).EndGetProgrammes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProgrammesCompleted(object state) {
            if ((this.GetProgrammesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProgrammesCompleted(this, new GetProgrammesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProgrammesAsync(tv.hagser.se_sl.TvWebService.GetProgrammesRequest request) {
            this.GetProgrammesAsync(request, null);
        }
        
        public void GetProgrammesAsync(tv.hagser.se_sl.TvWebService.GetProgrammesRequest request, object userState) {
            if ((this.onBeginGetProgrammesDelegate == null)) {
                this.onBeginGetProgrammesDelegate = new BeginOperationDelegate(this.OnBeginGetProgrammes);
            }
            if ((this.onEndGetProgrammesDelegate == null)) {
                this.onEndGetProgrammesDelegate = new EndOperationDelegate(this.OnEndGetProgrammes);
            }
            if ((this.onGetProgrammesCompletedDelegate == null)) {
                this.onGetProgrammesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProgrammesCompleted);
            }
            base.InvokeAsync(this.onBeginGetProgrammesDelegate, new object[] {
                        request}, this.onEndGetProgrammesDelegate, this.onGetProgrammesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override tv.hagser.se_sl.TvWebService.Service1Soap CreateChannel() {
            return new Service1SoapClientChannel(this);
        }
        
        private class Service1SoapClientChannel : ChannelBase<tv.hagser.se_sl.TvWebService.Service1Soap>, tv.hagser.se_sl.TvWebService.Service1Soap {
            
            public Service1SoapClientChannel(System.ServiceModel.ClientBase<tv.hagser.se_sl.TvWebService.Service1Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetInfo(string p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("GetInfo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginForceRefresh(string p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("ForceRefresh", _args, callback, asyncState);
                return _result;
            }
            
            public string EndForceRefresh(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ForceRefresh", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetChannels(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetChannels", _args, callback, asyncState);
                return _result;
            }
            
            public Channel[] EndGetChannels(System.IAsyncResult result) {
                object[] _args = new object[0];
                Channel[] _result = ((Channel[])(base.EndInvoke("GetChannels", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProgrammes(tv.hagser.se_sl.TvWebService.GetProgrammesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetProgrammes", _args, callback, asyncState);
                return _result;
            }
            
            public tv.hagser.se_sl.TvWebService.GetProgrammesResponse EndGetProgrammes(System.IAsyncResult result) {
                object[] _args = new object[0];
                tv.hagser.se_sl.TvWebService.GetProgrammesResponse _result = ((tv.hagser.se_sl.TvWebService.GetProgrammesResponse)(base.EndInvoke("GetProgrammes", _args, result)));
                return _result;
            }
        }
    }
}
